# Cross build using the same SDL/MiniGL ABI as OpenLara.
AMIGA_ROOT ?= /opt/amiga16-copy
DEV_ROOT ?= /mnt/d/dev
MGL_SDK ?= $(DEV_ROOT)/Pistorm3D/Pistorm3D_v12
SDL_ROOT ?= $(DEV_ROOT)/Pistorm3D/tests/sdl-fullscreen-fallback
SDL_LIB ?= $(SDL_ROOT)/build-fs/libSDL_libnix-fs.a
MIXER_ROOT := amiga/vendor/SDL_mixer
CC := $(AMIGA_ROOT)/bin/m68k-amigaos-gcc
TARGET := build-amiga/Doom64EX-Plus-MiniGL
CPPFLAGS := -DAMIGA_MINIGL -D__LEGACYGL__ -I src/engine -I amiga/include \
 -I$(MGL_SDK)/include -I$(SDL_ROOT)/include -I$(DEV_ROOT)/Pistorm3D/libSDL12-mgl/include \
 -I$(MIXER_ROOT) -I$(SDL_ROOT)/include/SDL -DWAV_MUSIC
CFLAGS := -std=gnu99 -O2 -m68060 -mhard-float -noixemul -fbbb=- \
 -fno-strict-aliasing -fomit-frame-pointer -ffunction-sections -fdata-sections -MMD -MP
LDFLAGS := -m68060 -mhard-float -noixemul -Wl,--gc-sections -Wl,-u,_KPrintF
LDLIBS := -Wl,--start-group build-amiga/libSDL_mixer.a build-amiga/libSDL-window.a \
 $(MGL_SDK)/libminigl_dispatch.a -lpng -lz -lm -ldebug -Wl,--end-group
OBJS := $(addprefix build-amiga/, i_system.o am_draw.o am_map.o info.o md5.o tables.o con_console.o con_cvar.o d_devstat.o d_main.o d_net.o f_finale.o in_stuff.o g_actions.o g_demo.o g_game.o g_settings.o wi_stuff.o m_cheat.o m_menu.o m_misc.o m_fixed.o m_keys.o m_password.o m_random.o m_shift.o net_client.o net_common.o net_io.o net_loop.o net_packet.o net_query.o net_server.o net_structure.o dgl.o gl_draw.o gl_main.o gl_texture.o sc_main.o p_ceilng.o p_doors.o p_enemy.o p_user.o p_floor.o p_inter.o p_lights.o p_macros.o p_map.o p_maputl.o p_mobj.o p_plats.o p_pspr.o p_saveg.o p_setup.o p_sight.o p_spec.o p_switch.o p_telept.o p_tick.o r_clipper.o r_drawlist.o r_lights.o r_main.o r_scene.o r_bsp.o r_sky.o r_things.o r_wipe.o s_sound.o st_stuff.o i_audio_amiga.o amiga_music.o i_main.o i_png.o i_video_amiga.o amiga_mouse.o amiga_gl.o w_file.o w_merge.o w_wad.o z_zone.o i_sdlinput.o  sha1.o)
.PHONY: all clean check
all: $(TARGET)
$(TARGET): $(OBJS) build-amiga/libSDL_mixer.a build-amiga/libSDL-window.a
	$(CC) $(LDFLAGS) $(OBJS) $(LDLIBS) -o $@
build-amiga/%.o: src/engine/%.c Makefile.amiga
	@mkdir -p build-amiga
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@
build-amiga/%.o: amiga/%.c Makefile.amiga
	@mkdir -p build-amiga
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@
check: $(TARGET)
	file $(TARGET)
	$(AMIGA_ROOT)/bin/m68k-amigaos-nm -u $(TARGET)
clean:
	rm -rf build-amiga
-include $(OBJS:.o=.d)

.PHONY: package
package: check
	python3 amiga/package.py

MIXER_UNITS := mixer music load_aiff load_voc effects_internal effect_position effect_stereoreverse wavestream
MIXER_OBJS := $(addprefix build-amiga/mixer/,$(addsuffix .o,$(MIXER_UNITS)))
build-amiga/mixer/%.o: $(MIXER_ROOT)/%.c Makefile.amiga
	@mkdir -p build-amiga/mixer
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@
build-amiga/libSDL_mixer.a: $(MIXER_OBJS)
	$(AMIGA_ROOT)/bin/m68k-amigaos-ar rcs $@ $^
-include $(MIXER_OBJS:.o=.d)

# Local SDL window fix: MiniGL presents at BorderLeft/BorderTop, so its
# window must use the normal RastPort origin rather than GimmeZeroZero.
build-amiga/SDL_cgxvideo.o: amiga/vendor/SDL-window/SDL_cgxvideo.c Makefile.amiga
	@mkdir -p build-amiga
	$(CC) -std=gnu99 -O2 -m68060 -mhard-float -noixemul \
	 -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types \
	 -Wno-error=int-conversion -DNOIXEMUL -DENABLE_CYBERGRAPHICS -DENABLE_AHI \
	 -DNO_SIGNAL_H -DNO_AMIGADEBUG -I$(SDL_ROOT) -I$(SDL_ROOT)/include \
	 -I$(SDL_ROOT)/include/SDL -I$(SDL_ROOT)/video/amigaos \
	 -I$(MGL_SDK)/include -I$(DEV_ROOT)/../amiga-gcc2/include -c $< -o $@
build-amiga/libSDL-window.a: $(SDL_LIB) build-amiga/SDL_cgxvideo.o
	cp $(SDL_LIB) $@
	$(AMIGA_ROOT)/bin/m68k-amigaos-ar rcs $@ build-amiga/SDL_cgxvideo.o
